/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Company;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author SIDDHI ANIL BHUJBAL
 */
public class MainApplication extends javax.swing.JFrame {

    /**
     * Creates new form MainApplication
     */
    private Connection conn;
    
    public MainApplication() {
        initComponents();
        connectToDatabase();
        loadTableData();
        initializeTable();
    }
    
    private void connectToDatabase(){
        try{
            String url="jdbc:mysql://localhost:3306/company_master";
            String user = "root";
            String password = "bvcoew";
            conn = DriverManager.getConnection(url, user, password);
            JOptionPane.showMessageDialog(this, "Connected to the database!");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Database connection failed: " + e.getMessage());
        }
    }
    
     private void loadTableData(){
         try{
             String sql = "SELECT * FROM companies";
             PreparedStatement ps = conn.prepareStatement(sql);
              ResultSet rs = ps.executeQuery();
                DefaultTableModel model = new DefaultTableModel(
                 new String[]{"com_code", "name", "address", "phone", "website", "description", "contact_person", "contact_person_desg"}, 
                0);
                while (rs.next()) {
                     model.addRow(new Object[]{
                    rs.getString("com_code"),
                    rs.getString("name"),
                    rs.getString("address"),
                    rs.getString("phone"),
                    rs.getString("website"),
                    rs.getString("description"),
                    rs.getString("contact_person"),
                    rs.getString("contact_person_desg")
                });
                }
                 tblcompany.setModel(model);
         }
         catch(SQLException e){
             JOptionPane.showMessageDialog(this, "Error loading table data: " + e.getMessage());
         }
     }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcompanymaster = new javax.swing.JLabel();
        pnlmain = new javax.swing.JPanel();
        lblcode = new java.awt.Label();
        lblname = new java.awt.Label();
        lbladdress = new java.awt.Label();
        lblphone = new java.awt.Label();
        lblwebsite = new java.awt.Label();
        lbldescription = new java.awt.Label();
        lblcontactperson = new java.awt.Label();
        lblpersondesc = new java.awt.Label();
        btnadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        txtcode = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taaddress = new javax.swing.JTextArea();
        txtwebsite = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tadesc = new javax.swing.JTextArea();
        txtcontactperson = new javax.swing.JTextField();
        txtcontactpersondesc = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblcompany = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Company Master");
        setBackground(new java.awt.Color(0, 204, 204));

        lblcompanymaster.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblcompanymaster.setText("COMPANY MASTER");

        pnlmain.setBackground(new java.awt.Color(0, 102, 102));
        pnlmain.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlmain.setForeground(new java.awt.Color(255, 255, 255));

        lblcode.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblcode.setForeground(new java.awt.Color(255, 255, 255));
        lblcode.setText("Company Code");

        lblname.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Company Name");

        lbladdress.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbladdress.setForeground(new java.awt.Color(255, 255, 255));
        lbladdress.setText("Company Address");

        lblphone.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblphone.setForeground(new java.awt.Color(255, 255, 255));
        lblphone.setText("Company Phone");

        lblwebsite.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblwebsite.setForeground(new java.awt.Color(255, 255, 255));
        lblwebsite.setText("Company Website");

        lbldescription.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbldescription.setForeground(new java.awt.Color(255, 255, 255));
        lbldescription.setText("Company Description");

        lblcontactperson.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblcontactperson.setForeground(new java.awt.Color(255, 255, 255));
        lblcontactperson.setText("Company Contact person");

        lblpersondesc.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblpersondesc.setForeground(new java.awt.Color(255, 255, 255));
        lblpersondesc.setText("Contact person Designation");

        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnadd.setText("Add");
        btnadd.setActionCommand("");
        btnadd.setOpaque(true);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        txtcode.setBackground(new java.awt.Color(0, 204, 204));
        txtcode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtname.setBackground(new java.awt.Color(0, 204, 204));
        txtname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtphone.setBackground(new java.awt.Color(0, 204, 204));
        txtphone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        taaddress.setBackground(new java.awt.Color(0, 204, 204));
        taaddress.setColumns(20);
        taaddress.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        taaddress.setRows(5);
        jScrollPane1.setViewportView(taaddress);

        txtwebsite.setBackground(new java.awt.Color(0, 204, 204));
        txtwebsite.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        tadesc.setBackground(new java.awt.Color(0, 204, 204));
        tadesc.setColumns(20);
        tadesc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tadesc.setRows(5);
        jScrollPane2.setViewportView(tadesc);

        txtcontactperson.setBackground(new java.awt.Color(0, 204, 204));
        txtcontactperson.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtcontactpersondesc.setBackground(new java.awt.Color(0, 204, 204));
        txtcontactpersondesc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlmainLayout = new javax.swing.GroupLayout(pnlmain);
        pnlmain.setLayout(pnlmainLayout);
        pnlmainLayout.setHorizontalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpersondesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcontactperson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcode, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblwebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontactperson, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtwebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontactpersondesc, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 215, Short.MAX_VALUE))
        );
        pnlmainLayout.setVerticalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(lblwebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(lbldescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblcontactperson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtwebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(txtcontactperson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblpersondesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontactpersondesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btnedit)
                    .addComponent(btndelete))
                .addGap(19, 19, 19))
        );

        tblcompany.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Company_code", "name", "address", "phone", "website", "description", "contact_person", "contact_persondesc"
            }
        ));
        tblcompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcompanyMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblcompany);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(649, 649, 649)
                .addComponent(lblcompanymaster, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblcompanymaster, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO companies (com_code, name, address, phone, website, description, contact_person, contact_person_desg) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, txtcode.getText());
            ps.setString(2, txtname.getText());
            ps.setString(3, taaddress.getText());
            ps.setString(4, txtphone.getText());
            ps.setString(5, txtwebsite.getText());
            ps.setString(6, tadesc.getText());
            ps.setString(7, txtcontactperson.getText());
            ps.setString(8, txtcontactpersondesc.getText());
             ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record added successfully!");
            loadTableData();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error adding record: " + e.getMessage());
        }
    }//GEN-LAST:event_btnaddActionPerformed

     
    
    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try{
             String sql = "UPDATE companies SET name=?, address=?, phone=?, website=?, description=?, contact_person=?, contact_person_desg=? WHERE com_code=?";
             PreparedStatement ps = conn.prepareStatement(sql);
              ps.setString(1, txtname.getText());
            ps.setString(2, taaddress.getText());
            ps.setString(3, txtphone.getText());
            ps.setString(4, txtwebsite.getText());
            ps.setString(5, tadesc.getText());
            ps.setString(6, txtcontactperson.getText());
            ps.setString(7, txtcontactpersondesc.getText());
            ps.setString(8, txtcode.getText());
            int rowsUpdated = ps.executeUpdate();
              if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Record updated successfully!");
                loadTableData(); // Refresh JTable data
            } else {
                JOptionPane.showMessageDialog(this, "Record not found!");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error updating record: " + e.getMessage());
        }
            
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try{
        String sql = "DELETE FROM companies WHERE com_code=?";
        PreparedStatement ps = conn.prepareStatement(sql);
         ps.setString(1, txtcode.getText());
          int rowsDeleted = ps.executeUpdate();
          if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Record deleted successfully!");
                loadTableData(); // Refresh JTable data
            } else {
                JOptionPane.showMessageDialog(this, "Record not found!");
            }
          
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error deleting record: " + e.getMessage()); 
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tblcompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcompanyMouseClicked
        // TODO add your handling code here:
          int selectedRow = tblcompany.getSelectedRow();
          if (selectedRow != -1) {
        String code = tblcompany.getValueAt(selectedRow, 0).toString();
        String name = tblcompany.getValueAt(selectedRow, 1).toString();
        String address = tblcompany.getValueAt(selectedRow, 2).toString();
        String phone = tblcompany.getValueAt(selectedRow, 3).toString();
        String website = tblcompany.getValueAt(selectedRow, 4).toString();
        String description = tblcompany.getValueAt(selectedRow, 5).toString();
        String contactPerson = tblcompany.getValueAt(selectedRow, 6).toString();
        String contactPersonDesg = tblcompany.getValueAt(selectedRow, 7).toString();
        
         txtcode.setText(code);
         txtname.setText(name);
         taaddress.setText(address);
         txtphone.setText(phone);
         txtwebsite.setText(website);
         tadesc.setText(description);
         txtcontactperson.setText(contactPerson);
         txtcontactpersondesc.setText(contactPersonDesg);
          }
    }//GEN-LAST:event_tblcompanyMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApplication().setVisible(true);
            }
        });
    }
    private void initializeTable() {
    // Set up the table model
    DefaultTableModel model = new DefaultTableModel(
        new String[]{"code", "name", "address", "phone", "website", "description", "contact_person", "contact_person_desg"}, 
        0
    );
    tblcompany.setModel(model);

    // Customize the table header
    customizeTableHeader();
}

private void customizeTableHeader() {
    JTableHeader tableHeader = tblcompany.getTableHeader();
    tableHeader.setFont(new Font("Arial", Font.BOLD, 14)); // Bold header font
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label lbladdress;
    private java.awt.Label lblcode;
    private javax.swing.JLabel lblcompanymaster;
    private java.awt.Label lblcontactperson;
    private java.awt.Label lbldescription;
    private java.awt.Label lblname;
    private java.awt.Label lblpersondesc;
    private java.awt.Label lblphone;
    private java.awt.Label lblwebsite;
    private javax.swing.JPanel pnlmain;
    private javax.swing.JTextArea taaddress;
    private javax.swing.JTextArea tadesc;
    private javax.swing.JTable tblcompany;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtcontactperson;
    private javax.swing.JTextField txtcontactpersondesc;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtwebsite;
    // End of variables declaration//GEN-END:variables
}
